// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: service_proofs.proto

package proofs_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OffchainProofsServiceClient is the client API for OffchainProofsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OffchainProofsServiceClient interface {
	VerifyBatchesSimulate(ctx context.Context, in *VerifyBatchesRequest, opts ...grpc.CallOption) (*Blank, error)
	StreamNewEvents(ctx context.Context, in *Blank, opts ...grpc.CallOption) (OffchainProofsService_StreamNewEventsClient, error)
	GetEvents(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*VerifyBatchesTrustedAggregatorEvents, error)
}

type offchainProofsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOffchainProofsServiceClient(cc grpc.ClientConnInterface) OffchainProofsServiceClient {
	return &offchainProofsServiceClient{cc}
}

func (c *offchainProofsServiceClient) VerifyBatchesSimulate(ctx context.Context, in *VerifyBatchesRequest, opts ...grpc.CallOption) (*Blank, error) {
	out := new(Blank)
	err := c.cc.Invoke(ctx, "/proofs.service.OffchainProofsService/VerifyBatchesSimulate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *offchainProofsServiceClient) StreamNewEvents(ctx context.Context, in *Blank, opts ...grpc.CallOption) (OffchainProofsService_StreamNewEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &OffchainProofsService_ServiceDesc.Streams[0], "/proofs.service.OffchainProofsService/StreamNewEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &offchainProofsServiceStreamNewEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type OffchainProofsService_StreamNewEventsClient interface {
	Recv() (*VerifyBatchesTrustedAggregatorEvent, error)
	grpc.ClientStream
}

type offchainProofsServiceStreamNewEventsClient struct {
	grpc.ClientStream
}

func (x *offchainProofsServiceStreamNewEventsClient) Recv() (*VerifyBatchesTrustedAggregatorEvent, error) {
	m := new(VerifyBatchesTrustedAggregatorEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *offchainProofsServiceClient) GetEvents(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*VerifyBatchesTrustedAggregatorEvents, error) {
	out := new(VerifyBatchesTrustedAggregatorEvents)
	err := c.cc.Invoke(ctx, "/proofs.service.OffchainProofsService/GetEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OffchainProofsServiceServer is the server API for OffchainProofsService service.
// All implementations must embed UnimplementedOffchainProofsServiceServer
// for forward compatibility
type OffchainProofsServiceServer interface {
	VerifyBatchesSimulate(context.Context, *VerifyBatchesRequest) (*Blank, error)
	StreamNewEvents(*Blank, OffchainProofsService_StreamNewEventsServer) error
	GetEvents(context.Context, *Blank) (*VerifyBatchesTrustedAggregatorEvents, error)
	mustEmbedUnimplementedOffchainProofsServiceServer()
}

// UnimplementedOffchainProofsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOffchainProofsServiceServer struct {
}

func (UnimplementedOffchainProofsServiceServer) VerifyBatchesSimulate(context.Context, *VerifyBatchesRequest) (*Blank, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyBatchesSimulate not implemented")
}
func (UnimplementedOffchainProofsServiceServer) StreamNewEvents(*Blank, OffchainProofsService_StreamNewEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamNewEvents not implemented")
}
func (UnimplementedOffchainProofsServiceServer) GetEvents(context.Context, *Blank) (*VerifyBatchesTrustedAggregatorEvents, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvents not implemented")
}
func (UnimplementedOffchainProofsServiceServer) mustEmbedUnimplementedOffchainProofsServiceServer() {}

// UnsafeOffchainProofsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OffchainProofsServiceServer will
// result in compilation errors.
type UnsafeOffchainProofsServiceServer interface {
	mustEmbedUnimplementedOffchainProofsServiceServer()
}

func RegisterOffchainProofsServiceServer(s grpc.ServiceRegistrar, srv OffchainProofsServiceServer) {
	s.RegisterService(&OffchainProofsService_ServiceDesc, srv)
}

func _OffchainProofsService_VerifyBatchesSimulate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyBatchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OffchainProofsServiceServer).VerifyBatchesSimulate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proofs.service.OffchainProofsService/VerifyBatchesSimulate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OffchainProofsServiceServer).VerifyBatchesSimulate(ctx, req.(*VerifyBatchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OffchainProofsService_StreamNewEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Blank)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OffchainProofsServiceServer).StreamNewEvents(m, &offchainProofsServiceStreamNewEventsServer{stream})
}

type OffchainProofsService_StreamNewEventsServer interface {
	Send(*VerifyBatchesTrustedAggregatorEvent) error
	grpc.ServerStream
}

type offchainProofsServiceStreamNewEventsServer struct {
	grpc.ServerStream
}

func (x *offchainProofsServiceStreamNewEventsServer) Send(m *VerifyBatchesTrustedAggregatorEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _OffchainProofsService_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Blank)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OffchainProofsServiceServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proofs.service.OffchainProofsService/GetEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OffchainProofsServiceServer).GetEvents(ctx, req.(*Blank))
	}
	return interceptor(ctx, in, info, handler)
}

// OffchainProofsService_ServiceDesc is the grpc.ServiceDesc for OffchainProofsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OffchainProofsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proofs.service.OffchainProofsService",
	HandlerType: (*OffchainProofsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyBatchesSimulate",
			Handler:    _OffchainProofsService_VerifyBatchesSimulate_Handler,
		},
		{
			MethodName: "GetEvents",
			Handler:    _OffchainProofsService_GetEvents_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamNewEvents",
			Handler:       _OffchainProofsService_StreamNewEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service_proofs.proto",
}
